spring:
  application:
    name: SpringSecurityExample
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

token:
  secret: askdjasldjaslkafjalksjlaksjglaksgjaigoiehwohiewksdnb5925927djidtt8ty
  lifetime: 3600000

